config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tickets#index"
  resources :tickets, except: [:destroy, :show]
  get "/tickets/manage", to: "tickets#manage"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, Ticket
      can :write, Ticket
      can :create, Ticket
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  resourcify
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_ticket, only: [:edit, :update]
  load_and_authorize_resource

  def index
    @tickets = current_user.tickets.order("created_at DESC")
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.create(ticket_params)
    @ticket.user = current_user

    if @ticket.save
      redirect_to tickets_path, :notice => "Ticket submitted!"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to tickets_manage_path, :notice => "Ticket handled"
    else
      render "edit"
    end
  end

  def manage
    if current_user.has_role? :admin
      @tickets = Ticket.all.order("created_at DESC")
      render "manage"
    else
      redirect_to root_path
    end
  end

  private
    def ticket_params
      params.require(:ticket).permit(:description, :is_processed)
    end

    def find_ticket
      @ticket = Ticket.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "partials/navbar" %>
    <%= render "partials/notification" %>
    <div class="app-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Chingu Tickets", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
      <% if current_user.has_role? :admin %>
        <li class="nav-item">
          <li class="nav-item">
            <%= link_to "Manage", tickets_manage_path, class: "nav-link" %>
          </li>
        </li>
      <% end %>
      <li class="nav-item">
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_notification.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/tickets/_edit_form.html.erb
<%= form_for @ticket do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :is_processed %>
    <%= f.check_box :is_processed %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/tickets/_form.html.erb
<%= form_for @ticket do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<div class="container">
  <h2>Handle a Ticket</h2>
  <%= render "edit_form" %>
</div>

app/views/tickets/index.html.erb
<div class="container">
  <h1>Chingu Tickets</h1>
  <p>Here's a list of all the tickets you've submitted.</p>
  <%= link_to "New Ticket", new_ticket_path, class: "btn btn-primary" %>
  
  <div class="row">
    <% @tickets.each do |ticket| %>
      <div class="card ticket-box">
        <div class="card-body">
          <p class="card-text"><%= ticket.description %></p>
          <p class="mb-2 text-muted"><%= ticket.created_at.strftime("%b %d %Y, %H:%M") %></p>
          <% if ticket.is_processed? %>
            <strong class="mb-2">Processed</strong>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/manage.html.erb
<div class="container">
  <h1>List of tickets</h1>
  <div class="row">
    <% @tickets.each do |ticket| %>
      <div class="card ticket-box">
        <div class="card-body">
          <p class="card-text"><%= ticket.description %></p>
          <p class="mb-2 text-muted">By <%= ticket.user.email %> - <%= ticket.created_at.strftime("%b %d %Y, %H:%M") %></p>
          <% if ticket.is_processed? %>
            <strong class="mb-2">Processed</strong>
          <% else %>
            <%= link_to "Manage", edit_ticket_path(ticket), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <h1>Send a new ticket</h1>
  <p>Please be as descriptive as possible, you <strong>won't</strong> be able to edit your ticket after you submit.</p>
  <%= render "form" %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>